160 fix all warnings during the build
BitcreditProtocol/Bitcredit-Core pull request #188
Opened 2024-10-24 17:36 UTC by zupzup

This is a draft and makes no sense to be reviewed until #186 is merged, since it's rebased to that - any changes necessary there will be rebased into this one as well.

This implements #160 and fixes all warnings and clippy warnings.

The changes were all done in a way so there is no logic change.

2024-10-24 20:47 UTC, mtbitcr requested changes
All good, only 2 minor comments

2024-10-24 20:47 UTC, mtbitcr commented on src/external/bitcoin.rs
> +                "https://blockstream.info/testnet/api/address/{address}/txs",
here no testnet

2024-10-24 20:47 UTC, mtbitcr commented on src/external/bitcoin.rs
> +                "https://blockstream.info/api/address/{address}/txs",
here testnet

2024-10-24 20:47 UTC, mtbitcr commented on src/external/bitcoin.rs
> +        Network::Bitcoin => "https://blockstream.info/testnet/api/blocks/tip/height",
here no testnet

2024-10-24 21:01 UTC, zupzup commented on src/external/bitcoin.rs
> +        Network::Bitcoin => "https://blockstream.info/testnet/api/blocks/tip/height",
uh, copy/paste error - nice catch, thanks! :+1:

2024-10-28 09:45 UTC, mtbitcr approved these changes

2024-10-28 09:45 UTC, merged